# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B -DskipTests package --file pom.xml

    - name: Build and Run Tests
      run: mvn test --batch-mode --fail-at-end

    - name: Publish Test Report
      if: always()
      uses: scacap/action-surefire-report@v1

    - name: upload JAR Artifact
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: ykologlu
        path: target/*.jar

    - name: Upload JAR to ftp Server
      if: success()
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: rathgeb.at
        user: f018212f
        password: HTL-Steyr4400
        localDir: ykologlu.jar